// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TogglTimeWeb.Server.Data;

#nullable disable

namespace TogglTimeWeb.Server.Migrations
{
    [DbContext(typeof(TogglTimeContext))]
    [Migration("20220227221316_Dummy")]
    partial class Dummy
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("TogglTimeWeb.Shared.TimeLimit", b =>
                {
                    b.Property<int>("TimeLimitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("TimeSpan")
                        .HasColumnType("TEXT");

                    b.HasKey("TimeLimitID");

                    b.ToTable("TimeLimits");
                });
#pragma warning restore 612, 618
        }
    }
}
